{{- if .Values.ingress.enabled -}}
{{- $fullName := include "monom-react.name" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}-ingress-security-config
spec:
  redirectToHttps:
    enabled: true
  sslPolicy: {{ $fullName }}-ssl-policy
{{- end }}
