apiVersion: v1
kind: Service
metadata:
  name: {{ include "monom-react.name" . }}
  labels:
    {{- include "monom-react.labels" . | nindent 4 }}
spec:
  type: {{ include "monom-react.service-type" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monom-react.selectorLabels" . | nindent 4 }}
