{{- $fullName := include "monom-spring.name" . -}}
{{- range .Values.ingress.backends }}
---
{{- $backendName := printf "%s-%s" $fullName .suffixName -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $backendName }}

spec:
  {{- if .sessionAffinityType }}
  sessionAffinity:
    affinityType: {{ .sessionAffinityType }}
  {{- end }}
  {{- if .timeoutSec }}
  timeoutSec: {{ .timeoutSec }}
  {{- end }}
  {{- if .drainingTimeoutSec }}
  connectionDraining:
    drainingTimeoutSec: {{ .drainingTimeoutSec }}
  {{- end }}
  healthCheck:
    {{- toYaml .healthcheck | nindent 4 }}
...
{{- end }}
