{{- if .Values.ingress.healthCheck -}}
{{- $fullName := include "monom-spring.name" . -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "monom-spring.labels" . | nindent 4 }}
spec:
  healthCheck:
    {{- toYaml .Values.ingress.healthCheck | nindent 4 }}
{{- end }}
