{{- if .Values.ingress.enabled -}}
{{- $fullName := include "monom-spring.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "monom-spring.labels" . | nindent 4 }}
  annotations:
    {{- include "monom-spring.ingress-annotations" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "ingress.host is required" .Values.ingress.host | quote }}
      http:
        paths:
          {{ range .Values.ingress.backends }}
          {{- $backendName := printf "%s-%s" $fullName .suffixName -}}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $backendName }}
                port:
                  number: {{ .port }}
          {{- end }}
{{- end }}
