{{- $fullName := include "monom-spring.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monom-spring.name" . }}
  labels:
    {{- include "monom-spring.labels" . | nindent 4 }}
  {{- if .Values.ingress.healthCheck }}
  annotations:
    cloud.google.com/backend-config: '{{- dict "default" $fullName | toJson }}'
  {{- end }}
spec:
  type: {{ include "monom-spring.service-type" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.additionalPorts }}
    {{- toYaml .Values.service.additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "monom-spring.selectorLabels" . | nindent 4 }}
