# Default values for monom-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  uri: ""

labelComponent: ""
labelPartOf: ""
instanceOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccountName: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env: {}

resources:
  limits:
    cpu: 750m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
    scheme: HTTP
  failureThreshold: 5
  initialDelaySeconds: 55
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
    scheme: HTTP
  failureThreshold: 2
  initialDelaySeconds: 90
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts: {}

volume: {}
