# Default values for monom-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  uri: ""

labelComponent: ""
labelPartOf: ""
instanceOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

serviceAccountName: ""

service:
  type: ClusterIP
  port: 80
  additionalPorts: []

ingress:
  enabled: false
  annotations: {}
  host: ""
  healthCheck: {}

env: {}
additionalPorts: []

resources:
  limits:
    cpu: 3
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 350Mi

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
    scheme: HTTP
  failureThreshold: 5
  initialDelaySeconds: 20
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
    scheme: HTTP
  failureThreshold: 2
  initialDelaySeconds: 25
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
rbac:
  enabled: false
  roleType: Role
  #roleType: ClusterRole
  bindType: RoleBinding
  #bindType: ClusterRoleBinding
  rules: {}

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts:
  - mountPath: /tmp/
    name: tmp-volume

volumes:
  - name: tmp-volume
    emptyDir: {}
