# Default values for awm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  uri: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

serviceAccountName: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  gkeAnnotationPrefix: ""
  enabled: true
  annotations: {}
  host: ""

env:
- name: WILDFLY_XMX
  value: 8096m
- name: DB_MAX_POOL_SIZE
  value: "100"
- name: PORT_HTTP
  value: "8080"
- name: PORT_HTTPS
  value: "8443"
- name: PORT_MANAGEMENT
  value: "9990"

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 1Gi

readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  failureThreshold: 5
  initialDelaySeconds: 55
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  failureThreshold: 2
  initialDelaySeconds: 90
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts: {}

volumes: {}