# Default values for monom-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  uri: ""

labelComponent: ""
labelPartOf: ""
instanceOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

serviceAccountName: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: ""

env: {}

resources:
  limits:
    cpu: 250m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 100Mi

readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  failureThreshold: 2
  initialDelaySeconds: 20
  periodSeconds: 25
  successThreshold: 1
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
