# Default values for monom-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  uri: ""

labelComponent: ""
labelPartOf: ""
instanceOverride: ""

schedule: ""
concurrencyPolicy: "Allow"
failedJobsHistoryLimit: 0
successfulJobsHistoryLimit: 0

restartPolicy: "Never"

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

serviceAccountName: ""

env: {}
additionalPorts: []

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 350Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts:
  - mountPath: /tmp/
    name: tmp-volume

volumes:
  - name: tmp-volume
    emptyDir: {}
