apiVersion: v1
kind: Service
metadata:
  name: {{ include "awm.name" . }}
  labels:
    {{- include "awm.labels" . | nindent 4 }}
spec:
  type: {{ include "awm.service-type" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.additionalPorts }}
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "awm.selectorLabels" . | nindent 4 }}
