{{- $fullName := include "terramonom-operator.name" . -}}
{{- $labels := include "terramonom-operator.labels" . -}}
{{- $command := .Values.subscriptionsTerramonomCommand -}}
{{- $environment := .Values.subscriptionsEnvironment -}}
{{- if .Values.subscriptions }}
---
apiVersion: terramonom.monom.ai/v1alpha1
kind: PubSubSubscriptions
metadata:
  name: {{ $fullName }}
  namespace: terramonom-operator-system
  labels:
    {{- $labels | nindent 4 }}
spec:
  command: {{ $command }}
  variables:
    project: monom-mvp-{{ $environment }}
    subscriptions:
      {{- range .Values.subscriptions }}
      - topic_name: {{ .topic_name }}
        subscription_name: {{ .subscription_name }}
        {{- if .ack_deadline_seconds }}
        ack_deadline_seconds: {{ .ack_deadline_seconds }}
        {{- end }}
        {{- if .message_retention_duration }}
        message_retention_duration: {{ .message_retention_duration }}
        {{- end }}
        {{- if .filter }}
        filter: {{ .filter }}
        {{- end }}
        {{- if .retain_acked_messages }}
        retain_acked_messages: {{ .retain_acked_messages }}
        {{- end }}
      {{- end }}
  backend:
    type: remote
    name: pubsubsubscriptions-{{ $fullName }}-{{ $environment }}
    organization: terramonom-operator-resources
    tokenSecretName: terramonom-operator-tfe
  serviceAccountName: terramonom-operator-pubsubsubscriptions
{{- end }}
